package metricguard_test

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// declRe finds any talos_* string literal in the source. Deliberately broader
// than `Name: "..."`: several collectors build families through a local helper
// (`g("talos_x", help)`), so anchoring on the struct field missed whole
// collectors. The superset can include a name quoted inside HELP text, which
// is harmless — such a name is documented anyway, so it never fires.
var declRe = regexp.MustCompile(`"(talos_[a-z0-9_]+)"`)

// docRe finds a metric name in a METRICS.md table cell or prose backtick.
var docRe = regexp.MustCompile("`(talos_[a-z0-9_]+)`")

// headerCountRe finds the family count in the METRICS.md header, e.g.
// "Every metric ... : **179 families**, ...".
var headerCountRe = regexp.MustCompile(`\*\*([0-9]+) families\*\*`)

// TestEveryMetricIsDocumented keeps docs/METRICS.md honest against the code.
//
// The reference is generated by hand from a live exposition, so it drifts
// silently: a family added without a table row is invisible to anyone reading
// the docs, and a family renamed leaves the old name documented and the new
// one absent. Both happened during development. This walks the source for
// metric declarations and the reference for names, and reports either
// direction of drift.
func TestEveryMetricIsDocumented(t *testing.T) {
	root := repoRoot(t)

	declared := map[string]string{} // metric -> file that declares it
	err := filepath.Walk(filepath.Join(root, "internal"), func(path string, _ os.FileInfo, err error) error {
		if err != nil || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return err
		}
		b, err := os.ReadFile(path) //nolint:gosec // walking our own source tree
		if err != nil {
			return err
		}
		for _, m := range declRe.FindAllSubmatch(b, -1) {
			declared[string(m[1])] = path
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk: %v", err)
	}
	// notMetrics are talos_* literals that are not metric names, and
	// computedNames are families whose name is built at runtime so no literal
	// exists to find. Both are small and each entry says why.
	notMetrics := map[string]bool{
		"talos_version": true, // a structured-log attribute key in nodes/talosclient.go
	}
	computedNames := map[string]bool{
		// sensors builds these with limitName(): talos_sensor_temperature_celsius
		// -> talos_sensor_temperature_limit_celsius, one per sensor kind.
		"talos_sensor_temperature_limit_celsius": true,
		"talos_sensor_fan_limit_rpm":             true,
		"talos_sensor_voltage_limit_volts":       true,
		"talos_sensor_power_limit_watts":         true,
		"talos_sensor_frequency_limit_hertz":     true,
	}
	for n := range notMetrics {
		delete(declared, n)
	}

	if len(declared) < 50 {
		t.Fatalf("only found %d metric declarations; the scanner is broken, not the docs", len(declared))
	}

	doc, err := os.ReadFile(filepath.Join(root, "docs", "METRICS.md")) //nolint:gosec // path is derived from the module root, not input
	if err != nil {
		t.Fatalf("read METRICS.md: %v", err)
	}
	documented := map[string]bool{}
	for _, m := range docRe.FindAllSubmatch(doc, -1) {
		documented[string(m[1])] = true
	}

	var undocumented, stale []string
	for name := range declared {
		if !documented[name] {
			undocumented = append(undocumented, name)
		}
	}
	for name := range documented {
		if _, ok := declared[name]; !ok && !computedNames[name] {
			stale = append(stale, name)
		}
	}
	sort.Strings(undocumented)
	sort.Strings(stale)

	for _, n := range undocumented {
		t.Errorf("%s is exported by %s but has no row in docs/METRICS.md", n, filepath.Base(declared[n]))
	}
	for _, n := range stale {
		t.Errorf("%s is documented in docs/METRICS.md but no longer exists in the code", n)
	}
	// computed families are built at runtime, so the literal scan above can
	// never flag them as undocumented. Check them explicitly, or a new
	// sensor-limit family could ship with no doc row and no test failing.
	for name := range computedNames {
		if !documented[name] {
			t.Errorf("%s is built at runtime but has no row in docs/METRICS.md", name)
		}
	}
}

// TestMetricsDocFamilyCount keeps the family count stated in the METRICS.md
// header in sync with the number of metric rows in the document. The count is
// otherwise easy to leave stale: it is not derivable from the code alone
// (several families are built at runtime), and the name-sync test above checks
// names, not the header's number.
func TestMetricsDocFamilyCount(t *testing.T) {
	root := repoRoot(t)
	doc, err := os.ReadFile(filepath.Join(root, "docs", "METRICS.md")) //nolint:gosec // path is derived from the module root, not input
	if err != nil {
		t.Fatalf("read METRICS.md: %v", err)
	}
	s := string(doc)

	m := headerCountRe.FindStringSubmatch(s)
	if m == nil {
		t.Fatal("could not find a '**N families**' count in the METRICS.md header")
	}
	stated, err := strconv.Atoi(m[1])
	if err != nil {
		t.Fatalf("parse family count %q: %v", m[1], err)
	}

	// One table row per family: "| `talos_...` | ... |".
	rows := 0
	for _, line := range strings.Split(s, "\n") {
		if strings.HasPrefix(line, "| `talos_") {
			rows++
		}
	}
	if stated != rows {
		t.Errorf("METRICS.md header states %d families but the tables list %d rows; keep the header in sync", stated, rows)
	}
}

// repoRoot walks up from the test's working directory to the module root.
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for range 6 {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		dir = filepath.Dir(dir)
	}
	t.Fatal("go.mod not found above the test directory")
	return ""
}
